---
homepage: https://github.com/kairichard/dotfiles/
version: 1.0
base: &basic
  - ackrc
  - bash
  - bash_profile
  - bashrc
  - tmux
  - tmux.conf
  - vim
  - vimrc

desktop: &desktop
  - gsdrc

vcs: &vcs
  - gitconfig
  - hgrc

ruby: &ruby
  - autotest
  - rspec
  - gemrc
  - irbrc

post:
  install: &vim_bundles
    - <%= @package_path/"vim/install_bundles" %>

osx: &osx
  config_files:
    - *basic
    - *desktop
    - *vcs
    - *ruby
    - iterm_server_profile_map

  post:
    install:
      - *vim_bundles
      - <%= @package_path/"bootstrap/osx/brew" %>
      - <%= @package_path/"bootstrap/osx/defaults" %>
      - <%= @package_path/"bootstrap/osx/fonts" %>
    update:
      - *vim_bundles
      - <%= @package_path/"bootstrap/osx/brew" %>

linux: &linux
  config_files:
    - *basic
    - *vcs
    - *ruby
  post:
    install:
      - *vim_bundles
      - <%= @package_path/"bootstrap/linux/debian_pkgs" %>
    update:
      - *vim_bundles

flavors:
  osx: *osx
  linux: *linux
