---
homepage: https://github.com/kairichard/dotfiles/
version: 1.0
base: &basic
  - ackrc
  - bash
  - bash_profile
  - bashrc
  - tmux
  - tmux.conf
  - vim
  - vimrc
  - bootstrap

desktop: &desktop
  - gsdrc

vcs: &vcs
  - gitconfig
  - hgrc

ruby: &ruby
  - autotest
  - rspec
  - gemrc
  - irbrc


vim_bundles: &vim_bundles
  - ~/.vim/install_bundles

osx: &osx
  config_files:
    - *basic
    - *desktop
    - *vcs
    - *ruby
    - iterm_server_profile_map

  setup:
    - *vim_bundles
    - ~/.bootstrap/osx/brew
    - ~/.bootstrap/osx/defaults
    - ~/.bootstrap/osx/fonts
    
  post:
    update:
      - *vim_bundles
      - ~/.bootstrap/osx/brew

linux: &linux
  config_files:
    - *basic
    - *vcs
    - *ruby
    
  setup:
    - *vim_bundles
    - ~/.bootstrap/linux/debian_pkgs
    
  post:
    update:
      - *vim_bundles

flavors:
  osx: *osx
  linux: *linux
